### ISSUE TITLE
about s3dis dataset

### ISSUE THREAD

**Issue by MRCHENWJ** [VinAIResearch/ISBNet#60]
Hello, I encountered an issue during preprocessing S3DIS data, how can I solve it?

(isbnet) root@autodl-container-58ce11bf52-76ea3b1f:~/autodl-tmp/ISBNet-master/dataset/s3dis# python prepare_s3dis.py
Traceback (most recent call last):
  File "prepare_s3dis.py", line 158, in <module>
    preprocess_s3dis(cfg.data_dir)
  File "prepare_s3dis.py", line 143, in preprocess_s3dis
    scene_data = read_scene_txt(scene_name, data_dir)
  File "prepare_s3dis.py", line 120, in read_scene_txt
    pts = np.loadtxt(os.path.join(data_dir + "/" + area, name, name + ".txt"))
  File "/root/miniconda3/envs/isbnet/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1148, in loadtxt
    for x in read_data(_loadtxt_chunksize):
  File "/root/miniconda3/envs/isbnet/lib/python3.7/site-packages/numpy/lib/npyio.py", line 999, in read_data
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "/root/miniconda3/envs/isbnet/lib/python3.7/site-packages/numpy/lib/npyio.py", line 999, in <listcomp>
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "/root/miniconda3/envs/isbnet/lib/python3.7/site-packages/numpy/lib/npyio.py", line 736, in floatconv
    return float(x)
ValueError: could not convert string to float: '167.\x1000000'

**Comment by robertod** [comment]
Hi @MRCHENWJ,

There are a few errors in the S3DIS dataset. To get the dataset working with the [current version](https://github.com/VinAIResearch/ISBNet/commit/44beb835a25b91d98a7b8ad35b90969b941b8f3b) of ISBNet you need to fix the following erroneous characters:
- Line 180389 of `Stanford3dDataset_v1.2_Aligned_Version\Area_5\hallway_6\Annotations\ceiling_1.txt`
- Line 741101 of `Stanford3dDataset_v1.2_Aligned_Version\Area_2\auditorium_1\auditorium_1.txt`
- Line 926337 of `Stanford3dDataset_v1.2_Aligned_Version\Area_3\hallway_2\hallway_2.txt`

You can use either the lines specified or the following regex `[\x00-\x1F]` to find these mistakes.

You will also have to remove the underscore in the file name `Stanford3dDataset_v1.2_Aligned_Version/Area_6/copyRoom_1/copy_Room_1.txt` such that it reads `copyRoom_1.txt`.

Best,
Roberto
